# Generated by Django 2.2.16 on 2022-06-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_title_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitle',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='title_id',
            new_name='title',
        ),
    ]
